### ISSUE TITLE
Error: Type 'DiagnosticableMixin' not found. class DateTimePickerTheme with DiagnosticableMixin {

### ISSUE THREAD

**Issue by qq543237999** [dylanwuzh/flutter-cupertino-date-picker#132]
flutter_cupertino_date_picker-1.0.26+2/lib/src/date_picker_theme.dart:23:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class DateTimePickerTheme with DiagnosticableMixin {
![image](https://user-images.githubusercontent.com/32667843/96075151-05097800-0edd-11eb-8d5c-34fa2ef5610f.png)

**Comment by TheHussein** [comment]
It's obsolete, someone made a fork that works, add this to your `pubspec.yaml` instead
```
dependencies:
  flutter:
    sdk: flutter
  flutter_cupertino_date_picker:
    git:
      url: https://github.com/imshashank/flutter-cupertino-date-picker # Repo
      ref: master # Branch name
```
